"use client"

import { Footer } from "@/components/Common/Footer"
import { Header } from "@/components/Common/Header"
import MenuHeader from "@/components/Common/MenuHeader"
import {
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbList,
    BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"
import Image from "next/image"

export default function SupportPolicyPage() {
    return (
        <div className="min-h-screen bg-background flex flex-col">
            <Header />
            <MenuHeader />
            <section className="w-full py-4 px-4 md:px-[104px] bg-[#E3E6E6]">
                <div className="flex flex-col md:flex-row items-center justify-between">
                    <h1 className="text-xl md:text-2xl font-bold text-center md:text-left">Trang chính sách hỗ trợ</h1>
                    <Breadcrumb className="mt-2 md:mt-0">
                        <BreadcrumbList>
                            <BreadcrumbItem>
                                <BreadcrumbLink href="/">
                                    Trang chủ
                                </BreadcrumbLink>
                            </BreadcrumbItem>
                            <BreadcrumbSeparator />
                            <BreadcrumbItem>
                                <BreadcrumbLink
                                    className="font-semibold"
                                    href="/support-policy"
                                >
                                    Chính sách hỗ trợ
                                </BreadcrumbLink>
                            </BreadcrumbItem>
                        </BreadcrumbList>
                    </Breadcrumb>
                </div>
            </section>
            <section className="w-full pb-4 px-4 md:px-[104px] bg-[#E3E6E6]">
                <div className="bg-white p-4 md:p-6 text-sm text-gray-600">
                    <span>
                        Thank you for shopping at{' '}
                        <Image
                            draggable={false}
                            src="https://img5.yeshen.cc/vn-alibaba/28/0a/28f8e540a990fac2f6dcdec0d4a0160df3f8cb0a.jpg"
                            alt="Logo"
                            width={44}
                            height={16}
                            style={{ display: 'inline-block', position: 'relative', bottom: '1px' }}
                        />
                    </span>
                    <br />
                    <br />
                    <span>If, for any reason, You are not completely satisfied with a purchase We invite You to review our policy on refunds and returns. This Return and Refund Policy was generated by TermsFeed Return and Refund Policy Generator.
                    </span>
                    <br />
                    <br />
                    <span>The following terms are applicable for any products that You purchased with Us.
                    </span>
                    <br />
                    <br />
                    <strong>
                        Interpretation and Definitions
                    </strong>
                    <br />
                    <br />
                    <span>
                        Interpretation
                    </span>
                    <br />
                    <br />
                    <span>
                        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                    </span>
                    <br />
                    <br />
                    <span>
                        Definitions
                    </span>
                    <br />
                    <br />
                    <span>
                        For the purposes of this Return and Refund Policy:
                    </span>
                    <br />
                    <br />
                    <span>
                        "Company" (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to{' '}
                    </span>
                    <br />
                    <br />
                    <span>
                        “Goods” refers to the items offered for sale on the Service.
                    </span>
                    <br />
                    <br />
                    <span>
                        “Orders” means a request by You to purchase Goods from Us.
                    </span>
                    <br />
                    <br />
                    <span>
                        “Service” refers to the Website.
                    </span>
                    <br />
                    <br />
                    <span>
                        “Website” refers to{' '}
                        <Image
                            draggable={false}
                            src="https://img5.yeshen.cc/vn-alibaba/28/0a/28f8e540a990fac2f6dcdec0d4a0160df3f8cb0a.jpg"
                            alt="Logo"
                            width={44}
                            height={16}
                            style={{ display: 'inline-block', position: 'relative', bottom: '1px' }}
                        />, accessible from amazonPro.com
                    </span>
                    <br />
                    <br />
                    <span>
                        “You” means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                    </span>
                    <br />
                    <br />
                    <span>
                        <strong>Your Order Cancellation Rights</strong>
                    </span>
                    <br />
                    <br />
                    <span>
                        You are entitled to cancel Your Order within 14 days without giving any reason for doing so.
                    </span>
                    <br />
                    <br />
                    <span>
                        The deadline for cancelling an Order is 14 days from the date on which You received the Goods or on which a third party you have appointed, who is not the carrier, takes possession of the product delivered.
                    </span>
                    <br />
                    <br />
                    <span>
                        In order to exercise Your right of cancellation, You must inform Us of your decision by means of a clear statement. You can inform us of your decision by:
                    </span>
                    <br />
                    <br />
                    <span>
                        By sending us an email: ds-reply@amazon-global-selling.com
                    </span>
                    <br />
                    <br />
                    <span>
                        We will reimburse You no later than 14 days from the day on which We receive the returned Goods. We will use the same means of payment as You used for the Order, and You will not incur any fees for such reimbursement.
                    </span>
                    <br />
                    <br />
                    <span>
                        <strong>Conditions for Returns</strong>
                    </span>
                    <br />
                    <br />
                    <span>
                        In order for the Goods to be eligible for a return, please make sure that:
                    </span>
                    <br />
                    <br />
                    <span>
                        The Goods were purchased in the last 14 days
                    </span>
                    <br />
                    <br />
                    <span>
                        The Goods are in the original packaging
                    </span>
                    <br />
                    <br />
                    <span>
                        The following Goods cannot be returned:
                    </span>
                    <br />
                    <br />
                    <span>
                        The supply of Goods made to Your specifications or clearly personalized.
                    </span>
                    <br />
                    <br />
                    <span>
                        The supply of Goods which according to their nature are not suitable to be returned, deteriorate rapidly or where the date of expiry is over.
                    </span>
                    <br />
                    <br />
                    <span>
                        The supply of Goods which are not suitable for return due to health protection or hygiene reasons and were unsealed after delivery.
                    </span>
                    <br />
                    <br />
                    <span>
                        The supply of Goods which are, after delivery, according to their nature, inseparably mixed with other items.
                    </span>
                    <br />
                    <br />
                    <span>
                        We reserve the right to refuse returns of any merchandise that does not meet the above return conditions in our sole discretion.
                    </span>
                </div>
            </section>
            <Footer />
        </div>
    )
}

