// Mock data based on the HTML content
export const mockData = [
    {
      id: "933499",
      name: "Ymosrh Mens Sweatshirt European Size Outdoor Casual Standing Collar Long-Sleeved Sweater Crewneck Sweatshirts, S-5XL - Clothes",
      image: "https://m.media-amazon.com/images/I/71BtQyJtIDL._AC_SL1500_.jpg",
      stock: 9203,
      sellingPrice: 21.89,
      purchasePrice: 17.51,
      profit: 4.38,
    },
    {
      id: "933473",
      name: "COOFANDY Mens Button Down Shirts Short Sleeve Casual Shirts Summer Beach Shirts Vacation Wedding Shirts with Pocket - Clothes",
      image: "https://m.media-amazon.com/images/I/818Hq5KSQQL._AC_SL1500_.jpg",
      stock: 8892,
      sellingPrice: 23.79,
      purchasePrice: 19.03,
      profit: 4.76,
    },
    {
      id: "933512",
      name: "COOFANDY Mens Casual Henley Shirts Short Sleeve Band Collar Shirt Summer Loose Beach T-Shirts - Clothes",
      image: "https://m.media-amazon.com/images/I/71XZD0RDYqL._AC_SL1500_.jpg",
      stock: 6454,
      sellingPrice: 23.99,
      purchasePrice: 19.19,
      profit: 4.8,
    },
    {
      id: "933477",
      name: "COOFANDY Mens Button Down Shirts Short Sleeve Casual Dress Shirts Untucked Summer Shirt with Pocket - Clothes",
      image: "https://m.media-amazon.com/images/I/71A9vM6YlSL._AC_SL1500_.jpg",
      stock: 1619,
      sellingPrice: 24.99,
      purchasePrice: 19.99,
      profit: 5.0,
    },
    {
      id: "933488",
      name: "PJ PAUL JONES Mens Shirt Jacket Lighweight Corduroy Overshirts Long Sleeve Button Down Shacket with Flap Pockets - Clothes",
      image: "https://m.media-amazon.com/images/I/71EZzGftuOL._AC_SL1500_.jpg",
      stock: 8762,
      sellingPrice: 24.99,
      purchasePrice: 19.99,
      profit: 5.0,
    },
    {
      id: "933516",
      name: "COOFANDY Mens Short Sleeve Knit Shirts Casual Button Down Polo Shirt Fashion Summer Beach Tops - Clothes",
      image: "https://m.media-amazon.com/images/I/91ufnXMxyrL._AC_SL1500_.jpg",
      stock: 1630,
      sellingPrice: 24.99,
      purchasePrice: 19.99,
      profit: 5.0,
    },
    {
      id: "933494",
      name: "COOFANDY Mens Hawaiian Floral Shirts Cotton Linen Button Down Tropical Holiday Beach Shirts - Clothes",
      image: "https://m.media-amazon.com/images/I/81rN7jSUgHS._AC_SL1500_.jpg",
      stock: 9940,
      sellingPrice: 25.17,
      purchasePrice: 20.14,
      profit: 5.03,
    },
    {
      id: "933503",
      name: "PJ PAUL JONES Mens T-Shirts Knit Short Sleeve Crewneck Shirt Casual Textured Pullover Tees - Clothes",
      image: "https://m.media-amazon.com/images/I/91Ll82XwoPL._AC_SL1500_.jpg",
      stock: 9114,
      sellingPrice: 25.4,
      purchasePrice: 20.32,
      profit: 5.08,
    },
    {
      id: "933492",
      name: "Wrangler Authentics Mens Long Sleeve Fleece Quarter-Zip Sweater - Clothes",
      image: "https://m.media-amazon.com/images/I/A1X74ZCjO+L._AC_SL1500_.jpg",
      stock: 4039,
      sellingPrice: 25.72,
      purchasePrice: 20.58,
      profit: 5.14,
    },
    {
      id: "933466",
      name: "COOFANDY Mens Casual Linen Beach Shirt Short Sleeve Button Down Summer Shirt Untucked Vacation Wedding Hawaiian Shirts - Clothes",
      image: "https://m.media-amazon.com/images/I/91r3TAEtb8L._AC_SL1500_.jpg",
      stock: 3888,
      sellingPrice: 25.99,
      purchasePrice: 20.79,
      profit: 5.2,
    },
    {
      id: "933470",
      name: "COOFANDY Mens Short Sleeve Button Down Shirts Summer Casual Textured Shirt Vacation Beach Wedding Shirts with Pocket - Clothes",
      image: "https://m.media-amazon.com/images/I/81je06Kyv5L._AC_SL1500_.jpg",
      stock: 8144,
      sellingPrice: 25.99,
      purchasePrice: 20.79,
      profit: 5.2,
    },
    {
      id: "933474",
      name: "COOFANDY Mens Short Sleeve Casual Button Down Shirts Textured Summer Beach Shirt with Pocket - Clothes",
      image: "https://m.media-amazon.com/images/I/81vs3CL+srL._AC_SL1500_.jpg",
      stock: 1595,
      sellingPrice: 25.99,
      purchasePrice: 20.79,
      profit: 5.2,
    },
  ]