
export const mockProducts = [
  {
    id: 1174866,
    name: "PJ Paul Jones Mens Polo Shirts Vintage Striped Lightweight Knitting Golf Shirts - Clothes",
    quantity: 2852,
    costPrice: "$19.19",
    sellingPrice: "$23.99",
    profit: "$4.80",
    status: "Đang bán",
    url: "https://shop.shop-worldwide-amz.top/product/ZnfGCXL68P",
  },
  {
    id: 1174041,
    name: "PJ PAUL JONES Mens Sweaters Crewneck Textured Knitted Raglan Sleeve Casual Pullover - Clothes",
    quantity: 4671,
    costPrice: "$16.79",
    sellingPrice: "$20.99",
    profit: "$4.20",
    status: "Đang bán",
    url: "https://shop.shop-worldwide-amz.top/product/GoEYCVzwZy",
  },
  {
    id: 1170979,
    name: "Luminara Moving Flame LED Flameless Tealight (1.4 x 2) Remote Ready Battery Operated Plastic LED Flameless Tea Light - Smooth Matte - Pearl Ivory (2-Pack Burgundy)",
    quantity: 1807,
    costPrice: "$1.60",
    sellingPrice: "$2.00",
    profit: "$0.40",
    status: "Đang bán",
    url: "https://shop.shop-worldwide-amz.top/product/2uwpU9xFz9",
  },
  {
    id: 1170980,
    name: "ASMAD Solar Garden Lights, 6 Pack 48 LEDs Solar Outdoor Lights, Christmas Decorations Lights, Solar Christmas Lights, Firefly Lights for Patio Pathway Outdoor Decor, Big Bulb Solar Swaying Light",
    quantity: 1989,
    costPrice: "$5.92",
    sellingPrice: "$7.40",
    profit: "$1.48",
    status: "Đang bán",
    url: "https://shop.shop-worldwide-amz.top/product/64tLEfSHMI",
  },
  {
    id: 1170981,
    name: "Christmas Decorations - Christmas Window Clings Christmas Decorations Indoor Christmas Decorations Clearance Snowflakes Christmas Window Decorations Stickers for Home Office Classroom",
    quantity: 5917,
    costPrice: "$4.79",
    sellingPrice: "$5.99",
    profit: "$1.20",
    status: "Đang bán",
    url: "https://shop.shop-worldwide-amz.top/product/SrWRv5TBte",
  },
  {
    id: 1170982,
    name: "Sanniu Led String Lights, Mini Battery Powered Copper Wire Starry Fairy Lights, Battery Operated Lights for Bedroom, Christmas, Parties, Wedding, Centerpiece, Decoration (5m/16ft Warm White),1 Pack",
    quantity: 6119,
    costPrice: "$5.59",
    sellingPrice: "$6.99",
    profit: "$1.40",
    status: "Đang bán",
    url: "https://shop.shop-worldwide-amz.top/product/FFBhqmt2Iq",
  },
  {
    id: 1170983,
    name: "Gr Window Clings Reusable 88 PCS Christmas Window Clings Gr Christmas Decorations Christmas Window Sticker Gr Window Decals Home School Office Gr Party, 8 sheets",
    quantity: 5340,
    costPrice: "$4.79",
    sellingPrice: "$5.99",
    profit: "$1.20",
    status: "Đang bán",
    url: "https://shop.shop-worldwide-amz.top/product/b1qwhkSgre",
  },
  {
    id: 1170984,
    name: "Large Print Christmas Coloring Book for Adults: Over 50 Simple, Easy, and Fun Christmas Holiday Coloring Pages for Adults and Seniors with Large Designs for Stress Relief and Relaxation",
    quantity: 1150,
    costPrice: "$5.59",
    sellingPrice: "$6.99",
    profit: "$1.40",
    status: "Đang bán",
    url: "https://shop.shop-worldwide-amz.top/product/PjQkDa2viU",
  },
  {
    id: 1170985,
    name: "Christmas Window Clings for Glass Christmas Window Decals Snowflakes 138 PCS Xmas Decals Decorations Clings Stickers for Christmas Decorations Snowflake Window Clings Winter Window Clings",
    quantity: 8248,
    costPrice: "$2.27",
    sellingPrice: "$2.84",
    profit: "$0.57",
    status: "Đang bán",
    url: "https://shop.shop-worldwide-amz.top/product/vUFyt1LION",
  },
  {
    id: 1170986,
    name: "Rudolph the Red-Nosed Reindeer (Rudolph the Red-Nosed Reindeer) (Little Golden Book)",
    quantity: 2339,
    costPrice: "$3.19",
    sellingPrice: "$3.99",
    profit: "$0.80",
    status: "Đang bán",
    url: "https://shop.shop-worldwide-amz.top/product/MLJ5Ii0vtZ",
  },
]

